import PDFDocument from "pdfkit";

const C = {
  primary: "#1e3a8a",
  text: "#1f2937",
  line: "#e5e7eb",
};

export const generatePdf = (data) =>
  new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margins: { top: 50, bottom: 70, left: 50, right: 50 },
        bufferPages: true,
        info: {
          Author: "NexoraAI",
          Title: data?.title || "Document",
        },
      });

      const chunks = [];
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const left = doc.page.margins.left;
      const width = doc.page.width - left - doc.page.margins.right;
      const bottomLimit = () => doc.page.height - doc.page.margins.bottom;

      //Header
      doc.rect(0, 0, doc.page.width, 130).fill(C.primary);

      doc
        .fillColor("#ffffff")
        .font("Helvetica-Bold")
        .fontSize(26)
        .text(data?.title || "Document", left, 40, { width });

      if (data?.subtitle) {
        doc
          .fillColor("#dbeafe")
          .font("Helvetica")
          .fontSize(12)
          .text(data.subtitle, left, doc.y + 6, { width });
      }

      doc.x = left;
      doc.y = 160;

      //Sections
      (data?.sections || []).forEach((section, i) => {
        if (doc.y > bottomLimit() - 100) doc.addPage();

        // heading
        doc
          .fillColor(C.primary)
          .font("Helvetica-Bold")
          .fontSize(16)
          .text(`${i + 1}. ${section?.heading || "Heading"}`, left, doc.y, {
            width,
          });

        // line below heading
        const lineY = doc.y + 3;
        doc
          .moveTo(left, lineY)
          .lineTo(left + width, lineY)
          .strokeColor(C.line)
          .lineWidth(1)
          .stroke();
        doc.y = lineY + 8;

        // bullet points
        doc.fillColor(C.text).font("Helvetica").fontSize(11);
        (section?.points || []).forEach((point) => {
          doc.text(`•  ${point}`, left + 10, doc.y, {
            width: width - 10,
            lineGap: 3,
          });
          doc.moveDown(0.2);
        });

        doc.x = left;
        doc.moveDown(1.2);
      });

      //Footer + page numbers
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);

        const oldBottom = doc.page.margins.bottom;
        doc.page.margins.bottom = 0;

        doc
          .font("Helvetica")
          .fontSize(9)
          .fillColor("#9ca3af")
          .text(
            `Generated by NexoraAI   |   Page ${i + 1} of ${range.count}`,
            left,
            doc.page.height - 40,
            { width, align: "center", lineBreak: false },
          );

        doc.page.margins.bottom = oldBottom;
      }

      doc.end();
    } catch (error) {
      console.log(`Error generating pdf ${error}`);
      reject(error);
    }
  });
